# Generated by Django 6.0.1 on 2026-04-03 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(choices=[('IP', 'Image & Video Processing'), ('CC', 'Cloud Computing'), ('PDP', 'PDP'), ('CN', 'Computer Networks'), ('TOC', 'Theory of Computation'), ('MP', 'Minor Project'), ('IP_LAB', 'Practical — Image & Video Processing'), ('CC_LAB', 'Practical — Cloud Computing'), ('CN_LAB', 'Practical — Computer Networks'), ('TOC_LAB', 'Practical — Theory of Computation'), ('APT', 'Aptitude'), ('CP', 'Competitive Programming')], max_length=10)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('project', 'Project')], default='theory', max_length=10)),
                ('batch', models.CharField(choices=[('ALL', 'All Students'), ('B1', 'Batch 1'), ('B2', 'Batch 2')], default='ALL', max_length=3)),
                ('room', models.CharField(default='Room 28', max_length=20)),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_sessions', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.timetableslot')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('slot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('IP', 'Image & Video Processing'), ('CC', 'Cloud Computing'), ('PDP', 'PDP'), ('CN', 'Computer Networks'), ('TOC', 'Theory of Computation'), ('MP', 'Minor Project'), ('IP_LAB', 'Practical — Image & Video Processing'), ('CC_LAB', 'Practical — Cloud Computing'), ('CN_LAB', 'Practical — Computer Networks'), ('TOC_LAB', 'Practical — Theory of Computation'), ('APT', 'Aptitude'), ('CP', 'Competitive Programming')], max_length=10)),
                ('total_classes', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
