# Generated by Django 6.0.1 on 2026-05-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancesummary_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesummary',
            name='subject',
            field=models.CharField(choices=[('IP', 'Image & Video Processing'), ('CC', 'Cloud Computing'), ('PDP', 'PDP'), ('CN', 'Computer Networks'), ('TOC', 'Theory of Computation'), ('MP', 'Minor Project'), ('IP_LAB', 'Practical — Image & Video Processing'), ('CC_LAB', 'Practical — Cloud Computing'), ('CN_LAB', 'Practical — Computer Networks'), ('TOC_LAB', 'Practical — Theory of Computation'), ('APT', 'Aptitude'), ('CP', 'Competitive Programming'), ('ML', 'Machine Learning'), ('CN_CS', 'Computer Networks (CS)'), ('CD', 'Compiler Design'), ('PM', 'Project Management'), ('DAL', 'DAL'), ('SDL', 'SDL'), ('CS_MP', 'Minor Project (CS)'), ('SIG_CP', 'Competitive Programming (CS)'), ('APTT', 'Aptitude (CS)'), ('DAL_LAB', 'Practical — DAL'), ('SDL_LAB', 'Practical — SDL'), ('ML_LAB', 'Practical — ML'), ('CN_CS_LAB', 'Practical — CN (CS)'), ('MCD', 'Machine Component Design'), ('TE', 'Thermal Engineering'), ('RET', 'Renewable Energy Technology'), ('RDBMS', 'RDBMS'), ('APT_ME', 'Aptitude (ME)'), ('MCD_LAB', 'Practical — Machine Component Design'), ('CAD_LAB', 'Practical — CAD'), ('RDBMS_LAB', 'Practical — RDBMS'), ('CGMM', 'Computer Graphics & Multimedia'), ('WMC', 'Wireless & Mobile Computing'), ('CD_IT', 'Compiler Design (IT)'), ('SE_IT', 'Software Engineering (IT)'), ('PP', 'PP'), ('AD', 'Android Development'), ('IT_MP', 'Minor Project (IT)'), ('CP_IT', 'Competitive Programming (IT)'), ('APTT_IT', 'Aptitude (IT)'), ('PDP_IT', 'PDP (IT)'), ('AND_LAB', 'Practical — Android/Python'), ('CGMM_LAB', 'Practical — CGMM'), ('WMC_LAB', 'Practical — WMC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='subject',
            field=models.CharField(choices=[('IP', 'Image & Video Processing'), ('CC', 'Cloud Computing'), ('PDP', 'PDP'), ('CN', 'Computer Networks'), ('TOC', 'Theory of Computation'), ('MP', 'Minor Project'), ('IP_LAB', 'Practical — Image & Video Processing'), ('CC_LAB', 'Practical — Cloud Computing'), ('CN_LAB', 'Practical — Computer Networks'), ('TOC_LAB', 'Practical — Theory of Computation'), ('APT', 'Aptitude'), ('CP', 'Competitive Programming'), ('ML', 'Machine Learning'), ('CN_CS', 'Computer Networks (CS)'), ('CD', 'Compiler Design'), ('PM', 'Project Management'), ('DAL', 'DAL'), ('SDL', 'SDL'), ('CS_MP', 'Minor Project (CS)'), ('SIG_CP', 'Competitive Programming (CS)'), ('APTT', 'Aptitude (CS)'), ('DAL_LAB', 'Practical — DAL'), ('SDL_LAB', 'Practical — SDL'), ('ML_LAB', 'Practical — ML'), ('CN_CS_LAB', 'Practical — CN (CS)'), ('MCD', 'Machine Component Design'), ('TE', 'Thermal Engineering'), ('RET', 'Renewable Energy Technology'), ('RDBMS', 'RDBMS'), ('APT_ME', 'Aptitude (ME)'), ('MCD_LAB', 'Practical — Machine Component Design'), ('CAD_LAB', 'Practical — CAD'), ('RDBMS_LAB', 'Practical — RDBMS'), ('CGMM', 'Computer Graphics & Multimedia'), ('WMC', 'Wireless & Mobile Computing'), ('CD_IT', 'Compiler Design (IT)'), ('SE_IT', 'Software Engineering (IT)'), ('PP', 'PP'), ('AD', 'Android Development'), ('IT_MP', 'Minor Project (IT)'), ('CP_IT', 'Competitive Programming (IT)'), ('APTT_IT', 'Aptitude (IT)'), ('PDP_IT', 'PDP (IT)'), ('AND_LAB', 'Practical — Android/Python'), ('CGMM_LAB', 'Practical — CGMM'), ('WMC_LAB', 'Practical — WMC')], max_length=15),
        ),
    ]
