# Generated by Django 6.0.1 on 2026-04-03 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('CN', 'Computer Networks'), ('TOC', 'Theory of Computation'), ('CC', 'Cloud Computing'), ('IP', 'Image & Video Processing'), ('TOC_LAB', 'Practical — Theory of Computation'), ('IP_LAB', 'Practical — Image & Video Processing'), ('CN_LAB', 'Practical — Computer Networks'), ('MP', 'Minor Project'), ('PDP', 'PDP'), ('CP', 'Competitive Programming')], max_length=20)),
                ('file', models.FileField(upload_to='notes/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
