# Generated by Django 6.0.1 on 2026-05-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('CN', 'Computer Networks'), ('TOC', 'Theory of Computation'), ('CC', 'Cloud Computing'), ('IP', 'Image & Video Processing'), ('TOC_LAB', 'Practical — Theory of Computation'), ('IP_LAB', 'Practical — Image & Video Processing'), ('CN_LAB', 'Practical — Computer Networks'), ('MP', 'Minor Project'), ('PDP', 'PDP'), ('CP', 'Competitive Programming'), ('TOM', 'Theory of Machines'), ('HMT', 'Heat & Mass Transfer'), ('FMM', 'Fluid Mechanics'), ('MFG', 'Manufacturing Technology'), ('CAD', 'CAD/CAM'), ('ME_MP', 'Mechanical Minor Project'), ('OS', 'Operating Systems'), ('DBMS', 'Database Management'), ('CN_CS', 'Computer Networks (CS)'), ('SE', 'Software Engineering'), ('AI', 'Artificial Intelligence'), ('CS_MP', 'CS Minor Project')], max_length=20),
        ),
    ]
