# Generated by Django 4.2.13 on 2026-06-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignment_announcement_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.note')),
            ],
            options={
                'ordering': ['note', 'chunk_index'],
            },
        ),
    ]
